language: rust
os:
    - linux
    - osx
cache: cargo

before_script:
    - rustup component add clippy rustfmt
script:
    - cargo test --verbose --all
    - cargo clippy
    - cargo fmt --all -- --check

