
mod element;
use element::{Element, IonRadius, State, Year};
#[cfg(test)]
mod test;

pub fn periodic_table() -> Vec<Element> {
    let mut result = Vec::new();
	result.push(Element {
		atomic_number: 1,
		symbol: "H",
		name: "Hydrogen",
		atomic_mass: "1.00794(4)",
		cpk_hex_color: "FFFFFF",
		electronic_configuration: "1s1",
		electronegativity: Some(2.2_f32),
		atomic_radius: Some(37),
		ion_radius: None,
		van_del_waals_radius: Some(120),
		ionization_energy: Some(1312),
		electron_affinity: Some(-73),
		oxidation_states: vec![-1, 1],
		standard_state: Some(State::Gas),
		bonding_type: "diatomic",
		melting_point: Some(14),
		boiling_point: Some(20),
		density: Some(0.0000899_f32),
		group_block: "nonmetal",
		year_discovered: Year::Known(1766),
	});
	result.push(Element {
		atomic_number: 2,
		symbol: "He",
		name: "Helium",
		atomic_mass: "4.002602(2)",
		cpk_hex_color: "D9FFFF",
		electronic_configuration: "1s2",
		electronegativity: None,
		atomic_radius: Some(32),
		ion_radius: None,
		van_del_waals_radius: Some(140),
		ionization_energy: Some(2372),
		electron_affinity: Some(0),
		oxidation_states: vec![],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: None,
		boiling_point: Some(4),
		density: Some(0.0001785_f32),
		group_block: "noble gas",
		year_discovered: Year::Known(1868),
	});
	result.push(Element {
		atomic_number: 3,
		symbol: "Li",
		name: "Lithium",
		atomic_mass: "6.941(2)",
		cpk_hex_color: "CC80FF",
		electronic_configuration: "[He] 2s1",
		electronegativity: Some(0.98_f32),
		atomic_radius: Some(134),
		ion_radius: Some(IonRadius::new(76_f32, "(+1)")),
		van_del_waals_radius: Some(182),
		ionization_energy: Some(520),
		electron_affinity: Some(-60),
		oxidation_states: vec![1],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(454),
		boiling_point: Some(1615),
		density: Some(0.535_f32),
		group_block: "alkali metal",
		year_discovered: Year::Known(1817),
	});
	result.push(Element {
		atomic_number: 4,
		symbol: "Be",
		name: "Beryllium",
		atomic_mass: "9.012182(3)",
		cpk_hex_color: "C2FF00",
		electronic_configuration: "[He] 2s2",
		electronegativity: Some(1.57_f32),
		atomic_radius: Some(90),
		ion_radius: Some(IonRadius::new(45_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(900),
		electron_affinity: Some(0),
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1560),
		boiling_point: Some(2743),
		density: Some(1.848_f32),
		group_block: "alkaline earth metal",
		year_discovered: Year::Known(1798),
	});
	result.push(Element {
		atomic_number: 5,
		symbol: "B",
		name: "Boron",
		atomic_mass: "10.811(7)",
		cpk_hex_color: "FFB5B5",
		electronic_configuration: "[He] 2s2 2p1",
		electronegativity: Some(2.04_f32),
		atomic_radius: Some(82),
		ion_radius: Some(IonRadius::new(27_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(801),
		electron_affinity: Some(-27),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "covalent network",
		melting_point: Some(2348),
		boiling_point: Some(4273),
		density: Some(2.46_f32),
		group_block: "metalloid",
		year_discovered: Year::Known(1807),
	});
	result.push(Element {
		atomic_number: 6,
		symbol: "C",
		name: "Carbon",
		atomic_mass: "12.0107(8)",
		cpk_hex_color: "909090",
		electronic_configuration: "[He] 2s2 2p2",
		electronegativity: Some(2.55_f32),
		atomic_radius: Some(77),
		ion_radius: Some(IonRadius::new(16_f32, "(+4)")),
		van_del_waals_radius: Some(170),
		ionization_energy: Some(1087),
		electron_affinity: Some(-154),
		oxidation_states: vec![-4, -3, -2, -1, 1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "covalent network",
		melting_point: Some(3823),
		boiling_point: Some(4300),
		density: Some(2.26_f32),
		group_block: "nonmetal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 7,
		symbol: "N",
		name: "Nitrogen",
		atomic_mass: "14.0067(2)",
		cpk_hex_color: "3050F8",
		electronic_configuration: "[He] 2s2 2p3",
		electronegativity: Some(3.04_f32),
		atomic_radius: Some(75),
		ion_radius: Some(IonRadius::new(146_f32, "(-3)")),
		van_del_waals_radius: Some(155),
		ionization_energy: Some(1402),
		electron_affinity: Some(-7),
		oxidation_states: vec![-3, -2, -1, 1, 2, 3, 4, 5],
		standard_state: Some(State::Gas),
		bonding_type: "diatomic",
		melting_point: Some(63),
		boiling_point: Some(77),
		density: Some(0.001251_f32),
		group_block: "nonmetal",
		year_discovered: Year::Known(1772),
	});
	result.push(Element {
		atomic_number: 8,
		symbol: "O",
		name: "Oxygen",
		atomic_mass: "15.9994(3)",
		cpk_hex_color: "FF0D0D",
		electronic_configuration: "[He] 2s2 2p4",
		electronegativity: Some(3.44_f32),
		atomic_radius: Some(73),
		ion_radius: Some(IonRadius::new(140_f32, "(-2)")),
		van_del_waals_radius: Some(152),
		ionization_energy: Some(1314),
		electron_affinity: Some(-141),
		oxidation_states: vec![-2, -1, 1, 2],
		standard_state: Some(State::Gas),
		bonding_type: "diatomic",
		melting_point: Some(55),
		boiling_point: Some(90),
		density: Some(0.001429_f32),
		group_block: "nonmetal",
		year_discovered: Year::Known(1774),
	});
	result.push(Element {
		atomic_number: 9,
		symbol: "F",
		name: "Fluorine",
		atomic_mass: "18.9984032(5)",
		cpk_hex_color: "90E050",
		electronic_configuration: "[He] 2s2 2p5",
		electronegativity: Some(3.98_f32),
		atomic_radius: Some(71),
		ion_radius: Some(IonRadius::new(133_f32, "(-1)")),
		van_del_waals_radius: Some(147),
		ionization_energy: Some(1681),
		electron_affinity: Some(-328),
		oxidation_states: vec![-1],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: Some(54),
		boiling_point: Some(85),
		density: Some(0.001696_f32),
		group_block: "halogen",
		year_discovered: Year::Known(1670),
	});
	result.push(Element {
		atomic_number: 10,
		symbol: "Ne",
		name: "Neon",
		atomic_mass: "20.1797(6)",
		cpk_hex_color: "B3E3F5",
		electronic_configuration: "[He] 2s2 2p6",
		electronegativity: None,
		atomic_radius: Some(69),
		ion_radius: None,
		van_del_waals_radius: Some(154),
		ionization_energy: Some(2081),
		electron_affinity: Some(0),
		oxidation_states: vec![],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: Some(25),
		boiling_point: Some(27),
		density: Some(0.0009_f32),
		group_block: "noble gas",
		year_discovered: Year::Known(1898),
	});
	result.push(Element {
		atomic_number: 11,
		symbol: "Na",
		name: "Sodium",
		atomic_mass: "22.98976928(2)",
		cpk_hex_color: "AB5CF2",
		electronic_configuration: "[Ne] 3s1",
		electronegativity: Some(0.93_f32),
		atomic_radius: Some(154),
		ion_radius: Some(IonRadius::new(102_f32, "(+1)")),
		van_del_waals_radius: Some(227),
		ionization_energy: Some(496),
		electron_affinity: Some(-53),
		oxidation_states: vec![-1, 1],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(371),
		boiling_point: Some(1156),
		density: Some(0.968_f32),
		group_block: "alkali metal",
		year_discovered: Year::Known(1807),
	});
	result.push(Element {
		atomic_number: 12,
		symbol: "Mg",
		name: "Magnesium",
		atomic_mass: "24.3050(6)",
		cpk_hex_color: "8AFF00",
		electronic_configuration: "[Ne] 3s2",
		electronegativity: Some(1.31_f32),
		atomic_radius: Some(130),
		ion_radius: Some(IonRadius::new(72_f32, "(+2)")),
		van_del_waals_radius: Some(173),
		ionization_energy: Some(738),
		electron_affinity: Some(0),
		oxidation_states: vec![1, 2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(923),
		boiling_point: Some(1363),
		density: Some(1.738_f32),
		group_block: "alkaline earth metal",
		year_discovered: Year::Known(1808),
	});
	result.push(Element {
		atomic_number: 13,
		symbol: "Al",
		name: "Aluminum",
		atomic_mass: "26.9815386(8)",
		cpk_hex_color: "BFA6A6",
		electronic_configuration: "[Ne] 3s2 3p1",
		electronegativity: Some(1.61_f32),
		atomic_radius: Some(118),
		ion_radius: Some(IonRadius::new(53.5_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(578),
		electron_affinity: Some(-43),
		oxidation_states: vec![1, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(933),
		boiling_point: Some(2792),
		density: Some(2.7_f32),
		group_block: "metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 14,
		symbol: "Si",
		name: "Silicon",
		atomic_mass: "28.0855(3)",
		cpk_hex_color: "F0C8A0",
		electronic_configuration: "[Ne] 3s2 3p2",
		electronegativity: Some(1.9_f32),
		atomic_radius: Some(111),
		ion_radius: Some(IonRadius::new(40_f32, "(+4)")),
		van_del_waals_radius: Some(210),
		ionization_energy: Some(787),
		electron_affinity: Some(-134),
		oxidation_states: vec![-4, -3, -2, -1, 1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1687),
		boiling_point: Some(3173),
		density: Some(2.33_f32),
		group_block: "metalloid",
		year_discovered: Year::Known(1854),
	});
	result.push(Element {
		atomic_number: 15,
		symbol: "P",
		name: "Phosphorus",
		atomic_mass: "30.973762(2)",
		cpk_hex_color: "FF8000",
		electronic_configuration: "[Ne] 3s2 3p3",
		electronegativity: Some(2.19_f32),
		atomic_radius: Some(106),
		ion_radius: Some(IonRadius::new(44_f32, "(+3)")),
		van_del_waals_radius: Some(180),
		ionization_energy: Some(1012),
		electron_affinity: Some(-72),
		oxidation_states: vec![-3, -2, -1, 1, 2, 3, 4, 5],
		standard_state: Some(State::Solid),
		bonding_type: "covalent network",
		melting_point: Some(317),
		boiling_point: Some(554),
		density: Some(1.823_f32),
		group_block: "nonmetal",
		year_discovered: Year::Known(1669),
	});
	result.push(Element {
		atomic_number: 16,
		symbol: "S",
		name: "Sulfur",
		atomic_mass: "32.065(5)",
		cpk_hex_color: "FFFF30",
		electronic_configuration: "[Ne] 3s2 3p4",
		electronegativity: Some(2.58_f32),
		atomic_radius: Some(102),
		ion_radius: Some(IonRadius::new(184_f32, "(-2)")),
		van_del_waals_radius: Some(180),
		ionization_energy: Some(1000),
		electron_affinity: Some(-200),
		oxidation_states: vec![-2, -1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "covalent network",
		melting_point: Some(388),
		boiling_point: Some(718),
		density: Some(1.96_f32),
		group_block: "nonmetal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 17,
		symbol: "Cl",
		name: "Chlorine",
		atomic_mass: "35.453(2)",
		cpk_hex_color: "1FF01F",
		electronic_configuration: "[Ne] 3s2 3p5",
		electronegativity: Some(3.16_f32),
		atomic_radius: Some(99),
		ion_radius: Some(IonRadius::new(181_f32, "(-1)")),
		van_del_waals_radius: Some(175),
		ionization_energy: Some(1251),
		electron_affinity: Some(-349),
		oxidation_states: vec![-1, 1, 2, 3, 4, 5, 6, 7],
		standard_state: Some(State::Gas),
		bonding_type: "covalent network",
		melting_point: Some(172),
		boiling_point: Some(239),
		density: Some(0.003214_f32),
		group_block: "halogen",
		year_discovered: Year::Known(1774),
	});
	result.push(Element {
		atomic_number: 18,
		symbol: "Ar",
		name: "Argon",
		atomic_mass: "39.948(1)",
		cpk_hex_color: "80D1E3",
		electronic_configuration: "[Ne] 3s2 3p6",
		electronegativity: None,
		atomic_radius: Some(97),
		ion_radius: None,
		van_del_waals_radius: Some(188),
		ionization_energy: Some(1521),
		electron_affinity: Some(0),
		oxidation_states: vec![],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: Some(84),
		boiling_point: Some(87),
		density: Some(0.001784_f32),
		group_block: "noble gas",
		year_discovered: Year::Known(1894),
	});
	result.push(Element {
		atomic_number: 19,
		symbol: "K",
		name: "Potassium",
		atomic_mass: "39.0983(1)",
		cpk_hex_color: "8F40D4",
		electronic_configuration: "[Ar] 4s1",
		electronegativity: Some(0.82_f32),
		atomic_radius: Some(196),
		ion_radius: Some(IonRadius::new(138_f32, "(+1)")),
		van_del_waals_radius: Some(275),
		ionization_energy: Some(419),
		electron_affinity: Some(-48),
		oxidation_states: vec![1],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(337),
		boiling_point: Some(1032),
		density: Some(0.856_f32),
		group_block: "alkali metal",
		year_discovered: Year::Known(1807),
	});
	result.push(Element {
		atomic_number: 20,
		symbol: "Ca",
		name: "Calcium",
		atomic_mass: "40.078(4)",
		cpk_hex_color: "3DFF00",
		electronic_configuration: "[Ar] 4s2",
		electronegativity: Some(1_f32),
		atomic_radius: Some(174),
		ion_radius: Some(IonRadius::new(100_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(590),
		electron_affinity: Some(-2),
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1115),
		boiling_point: Some(1757),
		density: Some(1.55_f32),
		group_block: "alkaline earth metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 21,
		symbol: "Sc",
		name: "Scandium",
		atomic_mass: "44.955912(6)",
		cpk_hex_color: "E6E6E6",
		electronic_configuration: "[Ar] 3d1 4s2",
		electronegativity: Some(1.36_f32),
		atomic_radius: Some(144),
		ion_radius: Some(IonRadius::new(74.5_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(633),
		electron_affinity: Some(-18),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1814),
		boiling_point: Some(3103),
		density: Some(2.985_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1876),
	});
	result.push(Element {
		atomic_number: 22,
		symbol: "Ti",
		name: "Titanium",
		atomic_mass: "47.867(1)",
		cpk_hex_color: "BFC2C7",
		electronic_configuration: "[Ar] 3d2 4s2",
		electronegativity: Some(1.54_f32),
		atomic_radius: Some(136),
		ion_radius: Some(IonRadius::new(86_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(659),
		electron_affinity: Some(-8),
		oxidation_states: vec![-1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1941),
		boiling_point: Some(3560),
		density: Some(4.507_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1791),
	});
	result.push(Element {
		atomic_number: 23,
		symbol: "V",
		name: "Vanadium",
		atomic_mass: "50.9415(1)",
		cpk_hex_color: "A6A6AB",
		electronic_configuration: "[Ar] 3d3 4s2",
		electronegativity: Some(1.63_f32),
		atomic_radius: Some(125),
		ion_radius: Some(IonRadius::new(79_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(651),
		electron_affinity: Some(-51),
		oxidation_states: vec![-1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2183),
		boiling_point: Some(3680),
		density: Some(6.11_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1803),
	});
	result.push(Element {
		atomic_number: 24,
		symbol: "Cr",
		name: "Chromium",
		atomic_mass: "51.9961(6)",
		cpk_hex_color: "8A99C7",
		electronic_configuration: "[Ar] 3d5 4s1",
		electronegativity: Some(1.66_f32),
		atomic_radius: Some(127),
		ion_radius: Some(IonRadius::new(80_f32, "(+2*)")),
		van_del_waals_radius: None,
		ionization_energy: Some(653),
		electron_affinity: Some(-64),
		oxidation_states: vec![-2, -1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2180),
		boiling_point: Some(2944),
		density: Some(7.14_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 25,
		symbol: "Mn",
		name: "Manganese",
		atomic_mass: "54.938045(5)",
		cpk_hex_color: "9C7AC7",
		electronic_configuration: "[Ar] 3d5 4s2",
		electronegativity: Some(1.55_f32),
		atomic_radius: Some(139),
		ion_radius: Some(IonRadius::new(67_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(717),
		electron_affinity: Some(0),
		oxidation_states: vec![-3, -2, -1, 1, 2, 3, 4, 5, 6, 7],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1519),
		boiling_point: Some(2334),
		density: Some(7.47_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1774),
	});
	result.push(Element {
		atomic_number: 26,
		symbol: "Fe",
		name: "Iron",
		atomic_mass: "55.845(2)",
		cpk_hex_color: "E06633",
		electronic_configuration: "[Ar] 3d6 4s2",
		electronegativity: Some(1.83_f32),
		atomic_radius: Some(125),
		ion_radius: Some(IonRadius::new(78_f32, "(+2*)")),
		van_del_waals_radius: None,
		ionization_energy: Some(763),
		electron_affinity: Some(-16),
		oxidation_states: vec![-2, -1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1811),
		boiling_point: Some(3134),
		density: Some(7.874_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 27,
		symbol: "Co",
		name: "Cobalt",
		atomic_mass: "58.933195(5)",
		cpk_hex_color: "F090A0",
		electronic_configuration: "[Ar] 3d7 4s2",
		electronegativity: Some(1.88_f32),
		atomic_radius: Some(126),
		ion_radius: Some(IonRadius::new(74.5_f32, "(+2*)")),
		van_del_waals_radius: None,
		ionization_energy: Some(760),
		electron_affinity: Some(-64),
		oxidation_states: vec![-1, 1, 2, 3, 4, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1768),
		boiling_point: Some(3200),
		density: Some(8.9_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 28,
		symbol: "Ni",
		name: "Nickel",
		atomic_mass: "58.6934(4)",
		cpk_hex_color: "50D050",
		electronic_configuration: "[Ar] 3d8 4s2",
		electronegativity: Some(1.91_f32),
		atomic_radius: Some(121),
		ion_radius: Some(IonRadius::new(69_f32, "(+2)")),
		van_del_waals_radius: Some(163),
		ionization_energy: Some(737),
		electron_affinity: Some(-112),
		oxidation_states: vec![-1, 1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1728),
		boiling_point: Some(3186),
		density: Some(8.908_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1751),
	});
	result.push(Element {
		atomic_number: 29,
		symbol: "Cu",
		name: "Copper",
		atomic_mass: "63.546(3)",
		cpk_hex_color: "C88033",
		electronic_configuration: "[Ar] 3d10 4s1",
		electronegativity: Some(1.9_f32),
		atomic_radius: Some(138),
		ion_radius: Some(IonRadius::new(77_f32, "(+1)")),
		van_del_waals_radius: Some(140),
		ionization_energy: Some(746),
		electron_affinity: Some(-118),
		oxidation_states: vec![1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1358),
		boiling_point: Some(3200),
		density: Some(8.92_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 30,
		symbol: "Zn",
		name: "Zinc",
		atomic_mass: "65.38(2)",
		cpk_hex_color: "7D80B0",
		electronic_configuration: "[Ar] 3d10 4s2",
		electronegativity: Some(1.65_f32),
		atomic_radius: Some(131),
		ion_radius: Some(IonRadius::new(74_f32, "(+2)")),
		van_del_waals_radius: Some(139),
		ionization_energy: Some(906),
		electron_affinity: Some(0),
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(693),
		boiling_point: Some(1180),
		density: Some(7.14_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1746),
	});
	result.push(Element {
		atomic_number: 31,
		symbol: "Ga",
		name: "Gallium",
		atomic_mass: "69.723(1)",
		cpk_hex_color: "C28F8F",
		electronic_configuration: "[Ar] 3d10 4s2 4p1",
		electronegativity: Some(1.81_f32),
		atomic_radius: Some(126),
		ion_radius: Some(IonRadius::new(62_f32, "(+3)")),
		van_del_waals_radius: Some(187),
		ionization_energy: Some(579),
		electron_affinity: Some(-29),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(303),
		boiling_point: Some(2477),
		density: Some(5.904_f32),
		group_block: "metal",
		year_discovered: Year::Known(1875),
	});
	result.push(Element {
		atomic_number: 32,
		symbol: "Ge",
		name: "Germanium",
		atomic_mass: "72.64(1)",
		cpk_hex_color: "668F8F",
		electronic_configuration: "[Ar] 3d10 4s2 4p2",
		electronegativity: Some(2.01_f32),
		atomic_radius: Some(122),
		ion_radius: Some(IonRadius::new(73_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(762),
		electron_affinity: Some(-119),
		oxidation_states: vec![-4, 1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1211),
		boiling_point: Some(3093),
		density: Some(5.323_f32),
		group_block: "metalloid",
		year_discovered: Year::Known(1886),
	});
	result.push(Element {
		atomic_number: 33,
		symbol: "As",
		name: "Arsenic",
		atomic_mass: "74.92160(2)",
		cpk_hex_color: "BD80E3",
		electronic_configuration: "[Ar] 3d10 4s2 4p3",
		electronegativity: Some(2.18_f32),
		atomic_radius: Some(119),
		ion_radius: Some(IonRadius::new(58_f32, "(+3)")),
		van_del_waals_radius: Some(185),
		ionization_energy: Some(947),
		electron_affinity: Some(-78),
		oxidation_states: vec![-3, 2, 3, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1090),
		boiling_point: Some(887),
		density: Some(5.727_f32),
		group_block: "metalloid",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 34,
		symbol: "Se",
		name: "Selenium",
		atomic_mass: "78.96(3)",
		cpk_hex_color: "FFA100",
		electronic_configuration: "[Ar] 3d10 4s2 4p4",
		electronegativity: Some(2.55_f32),
		atomic_radius: Some(116),
		ion_radius: Some(IonRadius::new(198_f32, "(-2)")),
		van_del_waals_radius: Some(190),
		ionization_energy: Some(941),
		electron_affinity: Some(-195),
		oxidation_states: vec![-2, 2, 4, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(494),
		boiling_point: Some(958),
		density: Some(4.819_f32),
		group_block: "nonmetal",
		year_discovered: Year::Known(1817),
	});
	result.push(Element {
		atomic_number: 35,
		symbol: "Br",
		name: "Bromine",
		atomic_mass: "79.904(1)",
		cpk_hex_color: "A62929",
		electronic_configuration: "[Ar] 3d10 4s2 4p5",
		electronegativity: Some(2.96_f32),
		atomic_radius: Some(114),
		ion_radius: Some(IonRadius::new(196_f32, "(-1)")),
		van_del_waals_radius: Some(185),
		ionization_energy: Some(1140),
		electron_affinity: Some(-325),
		oxidation_states: vec![-1, 1, 3, 4, 5, 7],
		standard_state: Some(State::Liquid),
		bonding_type: "covalent network",
		melting_point: Some(266),
		boiling_point: Some(332),
		density: Some(3.12_f32),
		group_block: "halogen",
		year_discovered: Year::Known(1826),
	});
	result.push(Element {
		atomic_number: 36,
		symbol: "Kr",
		name: "Krypton",
		atomic_mass: "83.798(2)",
		cpk_hex_color: "5CB8D1",
		electronic_configuration: "[Ar] 3d10 4s2 4p6",
		electronegativity: None,
		atomic_radius: Some(110),
		ion_radius: None,
		van_del_waals_radius: Some(202),
		ionization_energy: Some(1351),
		electron_affinity: Some(0),
		oxidation_states: vec![2],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: Some(116),
		boiling_point: Some(120),
		density: Some(0.00375_f32),
		group_block: "noble gas",
		year_discovered: Year::Known(1898),
	});
	result.push(Element {
		atomic_number: 37,
		symbol: "Rb",
		name: "Rubidium",
		atomic_mass: "85.4678(3)",
		cpk_hex_color: "702EB0",
		electronic_configuration: "[Kr] 5s1",
		electronegativity: Some(0.82_f32),
		atomic_radius: Some(211),
		ion_radius: Some(IonRadius::new(152_f32, "(+1)")),
		van_del_waals_radius: None,
		ionization_energy: Some(403),
		electron_affinity: Some(-47),
		oxidation_states: vec![1],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(312),
		boiling_point: Some(961),
		density: Some(1.532_f32),
		group_block: "alkali metal",
		year_discovered: Year::Known(1861),
	});
	result.push(Element {
		atomic_number: 38,
		symbol: "Sr",
		name: "Strontium",
		atomic_mass: "87.62(1)",
		cpk_hex_color: "00FF00",
		electronic_configuration: "[Kr] 5s2",
		electronegativity: Some(0.95_f32),
		atomic_radius: Some(192),
		ion_radius: Some(IonRadius::new(118_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(550),
		electron_affinity: Some(-5),
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1050),
		boiling_point: Some(1655),
		density: Some(2.63_f32),
		group_block: "alkaline earth metal",
		year_discovered: Year::Known(1790),
	});
	result.push(Element {
		atomic_number: 39,
		symbol: "Y",
		name: "Yttrium",
		atomic_mass: "88.90585(2)",
		cpk_hex_color: "94FFFF",
		electronic_configuration: "[Kr] 4d1 5s2",
		electronegativity: Some(1.22_f32),
		atomic_radius: Some(162),
		ion_radius: Some(IonRadius::new(90_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(600),
		electron_affinity: Some(-30),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1799),
		boiling_point: Some(3618),
		density: Some(4.472_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1794),
	});
	result.push(Element {
		atomic_number: 40,
		symbol: "Zr",
		name: "Zirconium",
		atomic_mass: "91.224(2)",
		cpk_hex_color: "94E0E0",
		electronic_configuration: "[Kr] 4d2 5s2",
		electronegativity: Some(1.33_f32),
		atomic_radius: Some(148),
		ion_radius: Some(IonRadius::new(72_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(640),
		electron_affinity: Some(-41),
		oxidation_states: vec![1, 2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2128),
		boiling_point: Some(4682),
		density: Some(6.511_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1789),
	});
	result.push(Element {
		atomic_number: 41,
		symbol: "Nb",
		name: "Niobium",
		atomic_mass: "92.90638(2)",
		cpk_hex_color: "73C2C9",
		electronic_configuration: "[Kr] 4d4 5s1",
		electronegativity: Some(1.6_f32),
		atomic_radius: Some(137),
		ion_radius: Some(IonRadius::new(72_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(652),
		electron_affinity: Some(-86),
		oxidation_states: vec![-1, 2, 3, 4, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2750),
		boiling_point: Some(5017),
		density: Some(8.57_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1801),
	});
	result.push(Element {
		atomic_number: 42,
		symbol: "Mo",
		name: "Molybdenum",
		atomic_mass: "95.96(2)",
		cpk_hex_color: "54B5B5",
		electronic_configuration: "[Kr] 4d5 5s1",
		electronegativity: Some(2.16_f32),
		atomic_radius: Some(145),
		ion_radius: Some(IonRadius::new(69_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(684),
		electron_affinity: Some(-72),
		oxidation_states: vec![-2, -1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2896),
		boiling_point: Some(4912),
		density: Some(10.28_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1778),
	});
	result.push(Element {
		atomic_number: 43,
		symbol: "Tc",
		name: "Technetium",
		atomic_mass: "[98]",
		cpk_hex_color: "3B9E9E",
		electronic_configuration: "[Kr] 4d5 5s2",
		electronegativity: Some(1.9_f32),
		atomic_radius: Some(156),
		ion_radius: Some(IonRadius::new(64.5_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(702),
		electron_affinity: Some(-53),
		oxidation_states: vec![-3, -1, 1, 2, 3, 4, 5, 6, 7],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2430),
		boiling_point: Some(4538),
		density: Some(11.5_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1937),
	});
	result.push(Element {
		atomic_number: 44,
		symbol: "Ru",
		name: "Ruthenium",
		atomic_mass: "101.07(2)",
		cpk_hex_color: "248F8F",
		electronic_configuration: "[Kr] 4d7 5s1",
		electronegativity: Some(2.2_f32),
		atomic_radius: Some(126),
		ion_radius: Some(IonRadius::new(68_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(710),
		electron_affinity: Some(-101),
		oxidation_states: vec![-2, 1, 2, 3, 4, 5, 6, 7, 8],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2607),
		boiling_point: Some(4423),
		density: Some(12.37_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1827),
	});
	result.push(Element {
		atomic_number: 45,
		symbol: "Rh",
		name: "Rhodium",
		atomic_mass: "102.90550(2)",
		cpk_hex_color: "0A7D8C",
		electronic_configuration: "[Kr] 4d8 5s1",
		electronegativity: Some(2.28_f32),
		atomic_radius: Some(135),
		ion_radius: Some(IonRadius::new(66.5_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(720),
		electron_affinity: Some(-110),
		oxidation_states: vec![-1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2237),
		boiling_point: Some(3968),
		density: Some(12.45_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1803),
	});
	result.push(Element {
		atomic_number: 46,
		symbol: "Pd",
		name: "Palladium",
		atomic_mass: "106.42(1)",
		cpk_hex_color: "6985",
		electronic_configuration: "[Kr] 4d10",
		electronegativity: Some(2.2_f32),
		atomic_radius: Some(131),
		ion_radius: Some(IonRadius::new(59_f32, "(+1)")),
		van_del_waals_radius: Some(163),
		ionization_energy: Some(804),
		electron_affinity: Some(-54),
		oxidation_states: vec![2, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1828),
		boiling_point: Some(3236),
		density: Some(12.023_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1803),
	});
	result.push(Element {
		atomic_number: 47,
		symbol: "Ag",
		name: "Silver",
		atomic_mass: "107.8682(2)",
		cpk_hex_color: "C0C0C0",
		electronic_configuration: "[Kr] 4d10 5s1",
		electronegativity: Some(1.93_f32),
		atomic_radius: Some(153),
		ion_radius: Some(IonRadius::new(115_f32, "(+1)")),
		van_del_waals_radius: Some(172),
		ionization_energy: Some(731),
		electron_affinity: Some(-126),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1235),
		boiling_point: Some(2435),
		density: Some(10.49_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 48,
		symbol: "Cd",
		name: "Cadmium",
		atomic_mass: "112.411(8)",
		cpk_hex_color: "FFD98F",
		electronic_configuration: "[Kr] 4d10 5s2",
		electronegativity: Some(1.69_f32),
		atomic_radius: Some(148),
		ion_radius: Some(IonRadius::new(95_f32, "(+2)")),
		van_del_waals_radius: Some(158),
		ionization_energy: Some(868),
		electron_affinity: Some(0),
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(594),
		boiling_point: Some(1040),
		density: Some(8.65_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1817),
	});
	result.push(Element {
		atomic_number: 49,
		symbol: "In",
		name: "Indium",
		atomic_mass: "114.818(3)",
		cpk_hex_color: "A67573",
		electronic_configuration: "[Kr] 4d10 5s2 5p1",
		electronegativity: Some(1.78_f32),
		atomic_radius: Some(144),
		ion_radius: Some(IonRadius::new(80_f32, "(+3)")),
		van_del_waals_radius: Some(193),
		ionization_energy: Some(558),
		electron_affinity: Some(-29),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(430),
		boiling_point: Some(2345),
		density: Some(7.31_f32),
		group_block: "metal",
		year_discovered: Year::Known(1863),
	});
	result.push(Element {
		atomic_number: 50,
		symbol: "Sn",
		name: "Tin",
		atomic_mass: "118.710(7)",
		cpk_hex_color: "668080",
		electronic_configuration: "[Kr] 4d10 5s2 5p2",
		electronegativity: Some(1.96_f32),
		atomic_radius: Some(141),
		ion_radius: Some(IonRadius::new(112_f32, "(+2)")),
		van_del_waals_radius: Some(217),
		ionization_energy: Some(709),
		electron_affinity: Some(-107),
		oxidation_states: vec![-4, 2, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(505),
		boiling_point: Some(2875),
		density: Some(7.31_f32),
		group_block: "metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 51,
		symbol: "Sb",
		name: "Antimony",
		atomic_mass: "121.760(1)",
		cpk_hex_color: "9E63B5",
		electronic_configuration: "[Kr] 4d10 5s2 5p3",
		electronegativity: Some(2.05_f32),
		atomic_radius: Some(138),
		ion_radius: Some(IonRadius::new(76_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(834),
		electron_affinity: Some(-103),
		oxidation_states: vec![-3, 3, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(904),
		boiling_point: Some(1860),
		density: Some(6.697_f32),
		group_block: "metalloid",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 52,
		symbol: "Te",
		name: "Tellurium",
		atomic_mass: "127.60(3)",
		cpk_hex_color: "D47A00",
		electronic_configuration: "[Kr] 4d10 5s2 5p4",
		electronegativity: Some(2.1_f32),
		atomic_radius: Some(135),
		ion_radius: Some(IonRadius::new(221_f32, "(-2)")),
		van_del_waals_radius: Some(206),
		ionization_energy: Some(869),
		electron_affinity: Some(-190),
		oxidation_states: vec![-2, 2, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(723),
		boiling_point: Some(1261),
		density: Some(6.24_f32),
		group_block: "metalloid",
		year_discovered: Year::Known(1782),
	});
	result.push(Element {
		atomic_number: 53,
		symbol: "I",
		name: "Iodine",
		atomic_mass: "126.90447(3)",
		cpk_hex_color: "940094",
		electronic_configuration: "[Kr] 4d10 5s2 5p5",
		electronegativity: Some(2.66_f32),
		atomic_radius: Some(133),
		ion_radius: Some(IonRadius::new(220_f32, "(-1)")),
		van_del_waals_radius: Some(198),
		ionization_energy: Some(1008),
		electron_affinity: Some(-295),
		oxidation_states: vec![-1, 1, 3, 5, 7],
		standard_state: Some(State::Solid),
		bonding_type: "covalent network",
		melting_point: Some(387),
		boiling_point: Some(457),
		density: Some(4.94_f32),
		group_block: "halogen",
		year_discovered: Year::Known(1811),
	});
	result.push(Element {
		atomic_number: 54,
		symbol: "Xe",
		name: "Xenon",
		atomic_mass: "131.293(6)",
		cpk_hex_color: "429EB0",
		electronic_configuration: "[Kr] 4d10 5s2 5p6",
		electronegativity: None,
		atomic_radius: Some(130),
		ion_radius: Some(IonRadius::new(48_f32, "(+8)")),
		van_del_waals_radius: Some(216),
		ionization_energy: Some(1170),
		electron_affinity: Some(0),
		oxidation_states: vec![2, 4, 6, 8],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: Some(161),
		boiling_point: Some(165),
		density: Some(0.0059_f32),
		group_block: "noble gas",
		year_discovered: Year::Known(1898),
	});
	result.push(Element {
		atomic_number: 55,
		symbol: "Cs",
		name: "Cesium",
		atomic_mass: "132.9054519(2)",
		cpk_hex_color: "57178F",
		electronic_configuration: "[Xe] 6s1",
		electronegativity: Some(0.79_f32),
		atomic_radius: Some(225),
		ion_radius: Some(IonRadius::new(167_f32, "(+1)")),
		van_del_waals_radius: None,
		ionization_energy: Some(376),
		electron_affinity: Some(-46),
		oxidation_states: vec![1],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(302),
		boiling_point: Some(944),
		density: Some(1.879_f32),
		group_block: "alkali metal",
		year_discovered: Year::Known(1860),
	});
	result.push(Element {
		atomic_number: 56,
		symbol: "Ba",
		name: "Barium",
		atomic_mass: "137.327(7)",
		cpk_hex_color: "00C900",
		electronic_configuration: "[Xe] 6s2",
		electronegativity: Some(0.89_f32),
		atomic_radius: Some(198),
		ion_radius: Some(IonRadius::new(135_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(503),
		electron_affinity: Some(-14),
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1000),
		boiling_point: Some(2143),
		density: Some(3.51_f32),
		group_block: "alkaline earth metal",
		year_discovered: Year::Known(1808),
	});
	result.push(Element {
		atomic_number: 57,
		symbol: "La",
		name: "Lanthanum",
		atomic_mass: "138.90547(7)",
		cpk_hex_color: "70D4FF",
		electronic_configuration: "[Xe] 5d1 6s2",
		electronegativity: Some(1.1_f32),
		atomic_radius: Some(169),
		ion_radius: Some(IonRadius::new(103.2_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(538),
		electron_affinity: Some(-48),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1193),
		boiling_point: Some(3737),
		density: Some(6.146_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1839),
	});
	result.push(Element {
		atomic_number: 58,
		symbol: "Ce",
		name: "Cerium",
		atomic_mass: "140.116(1)",
		cpk_hex_color: "FFFFC7",
		electronic_configuration: "[Xe] 4f1 5d1 6s2",
		electronegativity: Some(1.12_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(102_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(534),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1071),
		boiling_point: Some(3633),
		density: Some(6.689_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1803),
	});
	result.push(Element {
		atomic_number: 59,
		symbol: "Pr",
		name: "Praseodymium",
		atomic_mass: "140.90765(2)",
		cpk_hex_color: "D9FFC7",
		electronic_configuration: "[Xe] 4f3 6s2",
		electronegativity: Some(1.13_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(99_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(527),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1204),
		boiling_point: Some(3563),
		density: Some(6.64_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1885),
	});
	result.push(Element {
		atomic_number: 60,
		symbol: "Nd",
		name: "Neodymium",
		atomic_mass: "144.242(3)",
		cpk_hex_color: "C7FFC7",
		electronic_configuration: "[Xe] 4f4 6s2",
		electronegativity: Some(1.14_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(129_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(533),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1294),
		boiling_point: Some(3373),
		density: Some(7.01_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1885),
	});
	result.push(Element {
		atomic_number: 61,
		symbol: "Pm",
		name: "Promethium",
		atomic_mass: "[145]",
		cpk_hex_color: "A3FFC7",
		electronic_configuration: "[Xe] 4f5 6s2",
		electronegativity: Some(1.13_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(97_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(540),
		electron_affinity: Some(-50),
		oxidation_states: vec![3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1373),
		boiling_point: Some(3273),
		density: Some(7.264_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1947),
	});
	result.push(Element {
		atomic_number: 62,
		symbol: "Sm",
		name: "Samarium",
		atomic_mass: "150.36(2)",
		cpk_hex_color: "8FFFC7",
		electronic_configuration: "[Xe] 4f6 6s2",
		electronegativity: Some(1.17_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(122_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(545),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1345),
		boiling_point: Some(2076),
		density: Some(7.353_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1853),
	});
	result.push(Element {
		atomic_number: 63,
		symbol: "Eu",
		name: "Europium",
		atomic_mass: "151.964(1)",
		cpk_hex_color: "61FFC7",
		electronic_configuration: "[Xe] 4f7 6s2",
		electronegativity: Some(1.2_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(117_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(547),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1095),
		boiling_point: Some(1800),
		density: Some(5.244_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1901),
	});
	result.push(Element {
		atomic_number: 64,
		symbol: "Gd",
		name: "Gadolinium",
		atomic_mass: "157.25(3)",
		cpk_hex_color: "45FFC7",
		electronic_configuration: "[Xe] 4f7 5d1 6s2",
		electronegativity: Some(1.2_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(93.8_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(593),
		electron_affinity: Some(-50),
		oxidation_states: vec![1, 2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1586),
		boiling_point: Some(3523),
		density: Some(7.901_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1880),
	});
	result.push(Element {
		atomic_number: 65,
		symbol: "Tb",
		name: "Terbium",
		atomic_mass: "158.92535(2)",
		cpk_hex_color: "30FFC7",
		electronic_configuration: "[Xe] 4f9 6s2",
		electronegativity: Some(1.2_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(92.3_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(566),
		electron_affinity: Some(-50),
		oxidation_states: vec![1, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1629),
		boiling_point: Some(3503),
		density: Some(8.219_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1843),
	});
	result.push(Element {
		atomic_number: 66,
		symbol: "Dy",
		name: "Dysprosium",
		atomic_mass: "162.500(1)",
		cpk_hex_color: "1FFFC7",
		electronic_configuration: "[Xe] 4f10 6s2",
		electronegativity: Some(1.22_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(107_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(573),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1685),
		boiling_point: Some(2840),
		density: Some(8.551_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1886),
	});
	result.push(Element {
		atomic_number: 67,
		symbol: "Ho",
		name: "Holmium",
		atomic_mass: "164.93032(2)",
		cpk_hex_color: "00FF9C",
		electronic_configuration: "[Xe] 4f11 6s2",
		electronegativity: Some(1.23_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(90.1_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(581),
		electron_affinity: Some(-50),
		oxidation_states: vec![3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1747),
		boiling_point: Some(2973),
		density: Some(8.795_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1878),
	});
	result.push(Element {
		atomic_number: 68,
		symbol: "Er",
		name: "Erbium",
		atomic_mass: "167.259(3)",
		cpk_hex_color: "0.00E+00",
		electronic_configuration: "[Xe] 4f12 6s2",
		electronegativity: Some(1.24_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(89_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(589),
		electron_affinity: Some(-50),
		oxidation_states: vec![3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1770),
		boiling_point: Some(3141),
		density: Some(9.066_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1842),
	});
	result.push(Element {
		atomic_number: 69,
		symbol: "Tm",
		name: "Thulium",
		atomic_mass: "168.93421(2)",
		cpk_hex_color: "00D452",
		electronic_configuration: "[Xe] 4f13 6s2",
		electronegativity: Some(1.25_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(103_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(597),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1818),
		boiling_point: Some(2223),
		density: Some(9.321_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1879),
	});
	result.push(Element {
		atomic_number: 70,
		symbol: "Yb",
		name: "Ytterbium",
		atomic_mass: "173.054(5)",
		cpk_hex_color: "00BF38",
		electronic_configuration: "[Xe] 4f14 6s2",
		electronegativity: Some(1.1_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(102_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(603),
		electron_affinity: Some(-50),
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1092),
		boiling_point: Some(1469),
		density: Some(6.57_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1878),
	});
	result.push(Element {
		atomic_number: 71,
		symbol: "Lu",
		name: "Lutetium",
		atomic_mass: "174.9668(1)",
		cpk_hex_color: "00AB24",
		electronic_configuration: "[Xe] 4f14 5d1 6s2",
		electronegativity: Some(1.27_f32),
		atomic_radius: Some(160),
		ion_radius: Some(IonRadius::new(86.1_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(524),
		electron_affinity: Some(-50),
		oxidation_states: vec![3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1936),
		boiling_point: Some(3675),
		density: Some(9.841_f32),
		group_block: "lanthanoid",
		year_discovered: Year::Known(1907),
	});
	result.push(Element {
		atomic_number: 72,
		symbol: "Hf",
		name: "Hafnium",
		atomic_mass: "178.49(2)",
		cpk_hex_color: "4DC2FF",
		electronic_configuration: "[Xe] 4f14 5d2 6s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: Some(150),
		ion_radius: Some(IonRadius::new(71_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(659),
		electron_affinity: Some(0),
		oxidation_states: vec![2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2506),
		boiling_point: Some(4876),
		density: Some(13.31_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1923),
	});
	result.push(Element {
		atomic_number: 73,
		symbol: "Ta",
		name: "Tantalum",
		atomic_mass: "180.94788(2)",
		cpk_hex_color: "4DA6FF",
		electronic_configuration: "[Xe] 4f14 5d3 6s2",
		electronegativity: Some(1.5_f32),
		atomic_radius: Some(138),
		ion_radius: Some(IonRadius::new(72_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(761),
		electron_affinity: Some(-31),
		oxidation_states: vec![-1, 2, 3, 4, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(3290),
		boiling_point: Some(5731),
		density: Some(16.65_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1802),
	});
	result.push(Element {
		atomic_number: 74,
		symbol: "W",
		name: "Tungsten",
		atomic_mass: "183.84(1)",
		cpk_hex_color: "2194D6",
		electronic_configuration: "[Xe] 4f14 5d4 6s2",
		electronegativity: Some(2.36_f32),
		atomic_radius: Some(146),
		ion_radius: Some(IonRadius::new(66_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(770),
		electron_affinity: Some(-79),
		oxidation_states: vec![-2, -1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(3695),
		boiling_point: Some(5828),
		density: Some(19.25_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1783),
	});
	result.push(Element {
		atomic_number: 75,
		symbol: "Re",
		name: "Rhenium",
		atomic_mass: "186.207(1)",
		cpk_hex_color: "267DAB",
		electronic_configuration: "[Xe] 4f14 5d5 6s2",
		electronegativity: Some(1.9_f32),
		atomic_radius: Some(159),
		ion_radius: Some(IonRadius::new(63_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(760),
		electron_affinity: Some(-15),
		oxidation_states: vec![-3, -1, 1, 2, 3, 4, 5, 6, 7],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(3459),
		boiling_point: Some(5869),
		density: Some(21.02_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1925),
	});
	result.push(Element {
		atomic_number: 76,
		symbol: "Os",
		name: "Osmium",
		atomic_mass: "190.23(3)",
		cpk_hex_color: "266696",
		electronic_configuration: "[Xe] 4f14 5d6 6s2",
		electronegativity: Some(2.2_f32),
		atomic_radius: Some(128),
		ion_radius: Some(IonRadius::new(63_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(840),
		electron_affinity: Some(-106),
		oxidation_states: vec![-2, -1, 1, 2, 3, 4, 5, 6, 7, 8],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(3306),
		boiling_point: Some(5285),
		density: Some(22.61_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1803),
	});
	result.push(Element {
		atomic_number: 77,
		symbol: "Ir",
		name: "Iridium",
		atomic_mass: "192.217(3)",
		cpk_hex_color: "175487",
		electronic_configuration: "[Xe] 4f14 5d7 6s2",
		electronegativity: Some(2.2_f32),
		atomic_radius: Some(137),
		ion_radius: Some(IonRadius::new(68_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(880),
		electron_affinity: Some(-151),
		oxidation_states: vec![-3, -1, 1, 2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2739),
		boiling_point: Some(4701),
		density: Some(22.65_f32),
		group_block: "transition metal",
		year_discovered: Year::Known(1803),
	});
	result.push(Element {
		atomic_number: 78,
		symbol: "Pt",
		name: "Platinum",
		atomic_mass: "195.084(9)",
		cpk_hex_color: "D0D0E0",
		electronic_configuration: "[Xe] 4f14 5d9 6s1",
		electronegativity: Some(2.28_f32),
		atomic_radius: Some(128),
		ion_radius: Some(IonRadius::new(86_f32, "(+2)")),
		van_del_waals_radius: Some(175),
		ionization_energy: Some(870),
		electron_affinity: Some(-205),
		oxidation_states: vec![2, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2041),
		boiling_point: Some(4098),
		density: Some(21.09_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 79,
		symbol: "Au",
		name: "Gold",
		atomic_mass: "196.966569(4)",
		cpk_hex_color: "FFD123",
		electronic_configuration: "[Xe] 4f14 5d10 6s1",
		electronegativity: Some(2.54_f32),
		atomic_radius: Some(144),
		ion_radius: Some(IonRadius::new(137_f32, "(+1)")),
		van_del_waals_radius: Some(166),
		ionization_energy: Some(890),
		electron_affinity: Some(-223),
		oxidation_states: vec![-1, 1, 2, 3, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1337),
		boiling_point: Some(3129),
		density: Some(19.3_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 80,
		symbol: "Hg",
		name: "Mercury",
		atomic_mass: "200.59(2)",
		cpk_hex_color: "B8B8D0",
		electronic_configuration: "[Xe] 4f14 5d10 6s2",
		electronegativity: Some(2_f32),
		atomic_radius: Some(149),
		ion_radius: Some(IonRadius::new(119_f32, "(+1)")),
		van_del_waals_radius: Some(155),
		ionization_energy: Some(1007),
		electron_affinity: Some(0),
		oxidation_states: vec![1, 2, 4],
		standard_state: Some(State::Liquid),
		bonding_type: "metallic",
		melting_point: Some(234),
		boiling_point: Some(630),
		density: Some(13.534_f32),
		group_block: "transition metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 81,
		symbol: "Tl",
		name: "Thallium",
		atomic_mass: "204.3833(2)",
		cpk_hex_color: "A6544D",
		electronic_configuration: "[Xe] 4f14 5d10 6s2 6p1",
		electronegativity: Some(2.04_f32),
		atomic_radius: Some(148),
		ion_radius: Some(IonRadius::new(150_f32, "(+1)")),
		van_del_waals_radius: Some(196),
		ionization_energy: Some(589),
		electron_affinity: Some(-19),
		oxidation_states: vec![1, 3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(577),
		boiling_point: Some(1746),
		density: Some(11.85_f32),
		group_block: "metal",
		year_discovered: Year::Known(1861),
	});
	result.push(Element {
		atomic_number: 82,
		symbol: "Pb",
		name: "Lead",
		atomic_mass: "207.2(1)",
		cpk_hex_color: "575961",
		electronic_configuration: "[Xe] 4f14 5d10 6s2 6p2",
		electronegativity: Some(2.33_f32),
		atomic_radius: Some(147),
		ion_radius: Some(IonRadius::new(119_f32, "(+2)")),
		van_del_waals_radius: Some(202),
		ionization_energy: Some(716),
		electron_affinity: Some(-35),
		oxidation_states: vec![-4, 2, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(601),
		boiling_point: Some(2022),
		density: Some(11.34_f32),
		group_block: "metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 83,
		symbol: "Bi",
		name: "Bismuth",
		atomic_mass: "208.98040(1)",
		cpk_hex_color: "9E4FB5",
		electronic_configuration: "[Xe] 4f14 5d10 6s2 6p3",
		electronegativity: Some(2.02_f32),
		atomic_radius: Some(146),
		ion_radius: Some(IonRadius::new(103_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(703),
		electron_affinity: Some(-91),
		oxidation_states: vec![-3, 3, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(544),
		boiling_point: Some(1837),
		density: Some(9.78_f32),
		group_block: "metal",
		year_discovered: Year::Ancient,
	});
	result.push(Element {
		atomic_number: 84,
		symbol: "Po",
		name: "Polonium",
		atomic_mass: "[209]",
		cpk_hex_color: "AB5C00",
		electronic_configuration: "[Xe] 4f14 5d10 6s2 6p4",
		electronegativity: Some(2_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(94_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(812),
		electron_affinity: Some(-183),
		oxidation_states: vec![-2, 2, 4, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(527),
		boiling_point: Some(1235),
		density: Some(9.196_f32),
		group_block: "metalloid",
		year_discovered: Year::Known(1898),
	});
	result.push(Element {
		atomic_number: 85,
		symbol: "At",
		name: "Astatine",
		atomic_mass: "[210]",
		cpk_hex_color: "754F45",
		electronic_configuration: "[Xe] 4f14 5d10 6s2 6p5",
		electronegativity: Some(2.2_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(62_f32, "(+7)")),
		van_del_waals_radius: None,
		ionization_energy: Some(920),
		electron_affinity: Some(-270),
		oxidation_states: vec![-1, 1, 3, 5],
		standard_state: Some(State::Solid),
		bonding_type: "covalent network",
		melting_point: Some(575),
		boiling_point: None,
		density: None,
		group_block: "halogen",
		year_discovered: Year::Known(1940),
	});
	result.push(Element {
		atomic_number: 86,
		symbol: "Rn",
		name: "Radon",
		atomic_mass: "[222]",
		cpk_hex_color: "428296",
		electronic_configuration: "[Xe] 4f14 5d10 6s2 6p6",
		electronegativity: None,
		atomic_radius: Some(145),
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: Some(1037),
		electron_affinity: None,
		oxidation_states: vec![2],
		standard_state: Some(State::Gas),
		bonding_type: "atomic",
		melting_point: Some(202),
		boiling_point: Some(211),
		density: Some(0.00973_f32),
		group_block: "noble gas",
		year_discovered: Year::Known(1900),
	});
	result.push(Element {
		atomic_number: 87,
		symbol: "Fr",
		name: "Francium",
		atomic_mass: "[223]",
		cpk_hex_color: "420066",
		electronic_configuration: "[Rn] 7s1",
		electronegativity: Some(0.7_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(180_f32, "(+1)")),
		van_del_waals_radius: None,
		ionization_energy: Some(380),
		electron_affinity: None,
		oxidation_states: vec![1],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "alkali metal",
		year_discovered: Year::Known(1939),
	});
	result.push(Element {
		atomic_number: 88,
		symbol: "Ra",
		name: "Radium",
		atomic_mass: "[226]",
		cpk_hex_color: "007D00",
		electronic_configuration: "[Rn] 7s2",
		electronegativity: Some(0.9_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(148_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(509),
		electron_affinity: None,
		oxidation_states: vec![2],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(973),
		boiling_point: Some(2010),
		density: Some(5_f32),
		group_block: "alkaline earth metal",
		year_discovered: Year::Known(1898),
	});
	result.push(Element {
		atomic_number: 89,
		symbol: "Ac",
		name: "Actinium",
		atomic_mass: "[227]",
		cpk_hex_color: "70ABFA",
		electronic_configuration: "[Rn] 6d1 7s2",
		electronegativity: Some(1.1_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(112_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(499),
		electron_affinity: None,
		oxidation_states: vec![3],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1323),
		boiling_point: Some(3473),
		density: Some(10.07_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1899),
	});
	result.push(Element {
		atomic_number: 90,
		symbol: "Th",
		name: "Thorium",
		atomic_mass: "232.03806(2)",
		cpk_hex_color: "00BAFF",
		electronic_configuration: "[Rn] 6d2 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(94_f32, "(+4)")),
		van_del_waals_radius: None,
		ionization_energy: Some(587),
		electron_affinity: None,
		oxidation_states: vec![2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(2023),
		boiling_point: Some(5093),
		density: Some(11.724_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1828),
	});
	result.push(Element {
		atomic_number: 91,
		symbol: "Pa",
		name: "Protactinium",
		atomic_mass: "231.03588(2)",
		cpk_hex_color: "00A1FF",
		electronic_configuration: "[Rn] 5f2 6d1 7s2",
		electronegativity: Some(1.5_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(104_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(568),
		electron_affinity: None,
		oxidation_states: vec![3, 4, 5],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1845),
		boiling_point: Some(4273),
		density: Some(15.37_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1913),
	});
	result.push(Element {
		atomic_number: 92,
		symbol: "U",
		name: "Uranium",
		atomic_mass: "238.02891(3)",
		cpk_hex_color: "008FFF",
		electronic_configuration: "[Rn] 5f3 6d1 7s2",
		electronegativity: Some(1.38_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(102.5_f32, "(+3)")),
		van_del_waals_radius: Some(186),
		ionization_energy: Some(598),
		electron_affinity: None,
		oxidation_states: vec![3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1408),
		boiling_point: Some(4200),
		density: Some(19.05_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1789),
	});
	result.push(Element {
		atomic_number: 93,
		symbol: "Np",
		name: "Neptunium",
		atomic_mass: "[237]",
		cpk_hex_color: "0080FF",
		electronic_configuration: "[Rn] 5f4 6d1 7s2",
		electronegativity: Some(1.36_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(110_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(605),
		electron_affinity: None,
		oxidation_states: vec![3, 4, 5, 6, 7],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(917),
		boiling_point: Some(4273),
		density: Some(20.45_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1940),
	});
	result.push(Element {
		atomic_number: 94,
		symbol: "Pu",
		name: "Plutonium",
		atomic_mass: "[244]",
		cpk_hex_color: "006BFF",
		electronic_configuration: "[Rn] 5f6 7s2",
		electronegativity: Some(1.28_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(100_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(585),
		electron_affinity: None,
		oxidation_states: vec![3, 4, 5, 6, 7],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(913),
		boiling_point: Some(3503),
		density: Some(19.816_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1940),
	});
	result.push(Element {
		atomic_number: 95,
		symbol: "Am",
		name: "Americium",
		atomic_mass: "[243]",
		cpk_hex_color: "545CF2",
		electronic_configuration: "[Rn] 5f7 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(126_f32, "(+2)")),
		van_del_waals_radius: None,
		ionization_energy: Some(578),
		electron_affinity: None,
		oxidation_states: vec![2, 3, 4, 5, 6],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1449),
		boiling_point: Some(2284),
		density: None,
		group_block: "actinoid",
		year_discovered: Year::Known(1944),
	});
	result.push(Element {
		atomic_number: 96,
		symbol: "Cm",
		name: "Curium",
		atomic_mass: "[247]",
		cpk_hex_color: "785CE3",
		electronic_configuration: "[Rn] 5f7 6d1 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(97_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(581),
		electron_affinity: None,
		oxidation_states: vec![3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1618),
		boiling_point: Some(3383),
		density: Some(13.51_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1944),
	});
	result.push(Element {
		atomic_number: 97,
		symbol: "Bk",
		name: "Berkelium",
		atomic_mass: "[247]",
		cpk_hex_color: "8A4FE3",
		electronic_configuration: "[Rn] 5f9 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(96_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(601),
		electron_affinity: None,
		oxidation_states: vec![3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1323),
		boiling_point: None,
		density: Some(14.78_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1949),
	});
	result.push(Element {
		atomic_number: 98,
		symbol: "Cf",
		name: "Californium",
		atomic_mass: "[251]",
		cpk_hex_color: "A136D4",
		electronic_configuration: "[Rn] 5f10 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: Some(IonRadius::new(95_f32, "(+3)")),
		van_del_waals_radius: None,
		ionization_energy: Some(608),
		electron_affinity: None,
		oxidation_states: vec![2, 3, 4],
		standard_state: Some(State::Solid),
		bonding_type: "metallic",
		melting_point: Some(1173),
		boiling_point: None,
		density: Some(15.1_f32),
		group_block: "actinoid",
		year_discovered: Year::Known(1950),
	});
	result.push(Element {
		atomic_number: 99,
		symbol: "Es",
		name: "Einsteinium",
		atomic_mass: "[252]",
		cpk_hex_color: "B31FD4",
		electronic_configuration: "[Rn] 5f11 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: Some(619),
		electron_affinity: None,
		oxidation_states: vec![2, 3],
		standard_state: Some(State::Solid),
		bonding_type: "",
		melting_point: Some(1133),
		boiling_point: None,
		density: None,
		group_block: "actinoid",
		year_discovered: Year::Known(1952),
	});
	result.push(Element {
		atomic_number: 100,
		symbol: "Fm",
		name: "Fermium",
		atomic_mass: "[257]",
		cpk_hex_color: "B31FBA",
		electronic_configuration: "[Rn] 5f12 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: Some(627),
		electron_affinity: None,
		oxidation_states: vec![2, 3],
		standard_state: None,
		bonding_type: "",
		melting_point: Some(1800),
		boiling_point: None,
		density: None,
		group_block: "actinoid",
		year_discovered: Year::Known(1952),
	});
	result.push(Element {
		atomic_number: 101,
		symbol: "Md",
		name: "Mendelevium",
		atomic_mass: "[258]",
		cpk_hex_color: "B30DA6",
		electronic_configuration: "[Rn] 5f13 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: Some(635),
		electron_affinity: None,
		oxidation_states: vec![2, 3],
		standard_state: None,
		bonding_type: "",
		melting_point: Some(1100),
		boiling_point: None,
		density: None,
		group_block: "actinoid",
		year_discovered: Year::Known(1955),
	});
	result.push(Element {
		atomic_number: 102,
		symbol: "No",
		name: "Nobelium",
		atomic_mass: "[259]",
		cpk_hex_color: "BD0D87",
		electronic_configuration: "[Rn] 5f14 7s2",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: Some(642),
		electron_affinity: None,
		oxidation_states: vec![2, 3],
		standard_state: None,
		bonding_type: "",
		melting_point: Some(1100),
		boiling_point: None,
		density: None,
		group_block: "actinoid",
		year_discovered: Year::Known(1957),
	});
	result.push(Element {
		atomic_number: 103,
		symbol: "Lr",
		name: "Lawrencium",
		atomic_mass: "[262]",
		cpk_hex_color: "C70066",
		electronic_configuration: "[Rn] 5f14 7s2 7p1",
		electronegativity: Some(1.3_f32),
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![3],
		standard_state: None,
		bonding_type: "",
		melting_point: Some(1900),
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1961),
	});
	result.push(Element {
		atomic_number: 104,
		symbol: "Rf",
		name: "Rutherfordium",
		atomic_mass: "[267]",
		cpk_hex_color: "CC0059",
		electronic_configuration: "[Rn] 5f14 6d2 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![4],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1969),
	});
	result.push(Element {
		atomic_number: 105,
		symbol: "Db",
		name: "Dubnium",
		atomic_mass: "[268]",
		cpk_hex_color: "D1004F",
		electronic_configuration: "[Rn] 5f14 6d3 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1967),
	});
	result.push(Element {
		atomic_number: 106,
		symbol: "Sg",
		name: "Seaborgium",
		atomic_mass: "[271]",
		cpk_hex_color: "D90045",
		electronic_configuration: "[Rn] 5f14 6d4 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1974),
	});
	result.push(Element {
		atomic_number: 107,
		symbol: "Bh",
		name: "Bohrium",
		atomic_mass: "[272]",
		cpk_hex_color: "E00038",
		electronic_configuration: "[Rn] 5f14 6d5 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1976),
	});
	result.push(Element {
		atomic_number: 108,
		symbol: "Hs",
		name: "Hassium",
		atomic_mass: "[270]",
		cpk_hex_color: "E6002E",
		electronic_configuration: "[Rn] 5f14 6d6 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1984),
	});
	result.push(Element {
		atomic_number: 109,
		symbol: "Mt",
		name: "Meitnerium",
		atomic_mass: "[276]",
		cpk_hex_color: "EB0026",
		electronic_configuration: "[Rn] 5f14 6d7 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1982),
	});
	result.push(Element {
		atomic_number: 110,
		symbol: "Ds",
		name: "Darmstadtium",
		atomic_mass: "[281]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d9 7s1",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1994),
	});
	result.push(Element {
		atomic_number: 111,
		symbol: "Rg",
		name: "Roentgenium",
		atomic_mass: "[280]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s1",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1994),
	});
	result.push(Element {
		atomic_number: 112,
		symbol: "Cn",
		name: "Copernicium",
		atomic_mass: "[285]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "transition metal",
		year_discovered: Year::Known(1996),
	});
	result.push(Element {
		atomic_number: 113,
		symbol: "Nh",
		name: "Nihonium",
		atomic_mass: "[284]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2 7p1",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "post-transition metal",
		year_discovered: Year::Known(2003),
	});
	result.push(Element {
		atomic_number: 114,
		symbol: "Fl",
		name: "Flerovium",
		atomic_mass: "[289]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2 7p2",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "post-transition metal",
		year_discovered: Year::Known(1998),
	});
	result.push(Element {
		atomic_number: 115,
		symbol: "Mc",
		name: "Moscovium",
		atomic_mass: "[288]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2 7p3",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "post-transition metal",
		year_discovered: Year::Known(2003),
	});
	result.push(Element {
		atomic_number: 116,
		symbol: "Lv",
		name: "Livermorium",
		atomic_mass: "[293]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2 7p4",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "post-transition metal",
		year_discovered: Year::Known(2000),
	});
	result.push(Element {
		atomic_number: 117,
		symbol: "Ts",
		name: "Tennessine",
		atomic_mass: "[294]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2 7p5",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "post-transition metal",
		year_discovered: Year::Known(2010),
	});
	result.push(Element {
		atomic_number: 118,
		symbol: "Og",
		name: "Oganesson",
		atomic_mass: "[294]",
		cpk_hex_color: "",
		electronic_configuration: "[Rn] 5f14 6d10 7s2 7p6",
		electronegativity: None,
		atomic_radius: None,
		ion_radius: None,
		van_del_waals_radius: None,
		ionization_energy: None,
		electron_affinity: None,
		oxidation_states: vec![],
		standard_state: None,
		bonding_type: "",
		melting_point: None,
		boiling_point: None,
		density: None,
		group_block: "noble gas",
		year_discovered: Year::Known(2002),
	});

    result
}